import { type NextPage } from "next";
import Head from "next/head";
import {
  BookOpenIcon,
  CodeBracketIcon,
  ShareIcon,
} from "@heroicons/react/24/outline";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="items-top darkbg-gray-900 relative flex min-h-screen justify-center bg-slate-100 py-4 sm:items-center sm:pt-0">
        <div className="absolute top-6 right-6">
          <Link href="/auth/login" className="text-sm text-gray-700 underline ">
            Login
          </Link>
          <Link
            href="/auth/register"
            className="ml-4 text-sm text-gray-700 underline "
          >
            Register
          </Link>
        </div>
        <div className="mx-auto max-w-6xl sm:px-6 lg:px-8">
          <div className="flex justify-center pt-8 sm:justify-start sm:pt-0">
            <h1 className="text-6xl font-bold ">T3 - Breeze</h1>
          </div>

          <div className="mt-8 overflow-hidden bg-white shadow  sm:rounded-lg">
            <div className="grid grid-cols-1 md:grid-cols-2">
              <div className="p-6">
                <div className="flex items-center">
                  <BookOpenIcon className="h-8 w-8 text-gray-500" />
                  <div className="ml-4 text-lg font-semibold leading-7">
                    <a
                      href="https://nextjs.org/docs"
                      className="text-gray-900 underline "
                    >
                      Next.js Docs
                    </a>
                  </div>
                </div>

                <div className="ml-12">
                  <div className="mt-2 text-sm text-gray-600 ">
                    Next.js gives you the best developer experience with all the
                    features you need for production: hybrid static &amp; server
                    rendering, TypeScript support, smart bundling, route
                    pre-fetching, and more. No config needed.
                  </div>
                </div>
              </div>

              <div className="border-t border-gray-200 p-6  md:border-t-0 md:border-l">
                <div className="flex items-center">
                  <BookOpenIcon className="h-8 w-8 text-gray-500" />
                  <div className="ml-4 text-lg font-semibold leading-7">
                    <a
                      href="https://create.t3.gg/"
                      className="text-gray-900 underline "
                    >
                      Create T3 App
                    </a>
                  </div>
                </div>

                <div className="ml-12">
                  <div className="mt-2 text-sm text-gray-600 ">
                    The “T3 Stack” is a web development stack focused on
                    simplicity, modularity, and full-stack typesafety. The core
                    pieces being used are TypeScript, tRPC, TanstackQuery and
                    Prisma.
                  </div>
                </div>
              </div>

              <div className="border-t border-gray-200 p-6 ">
                <div className="flex items-center">
                  <BookOpenIcon className="h-8 w-8 text-gray-500" />
                  <div className="ml-4 text-lg font-semibold leading-7">
                    <a
                      href="https://laravel-news.com/"
                      className="text-gray-900 underline "
                    >
                      Tailwind Docs
                    </a>
                  </div>
                </div>

                <div className="ml-12">
                  <div className="mt-2 text-sm text-gray-600 ">
                    Tailwind CSS is a highly customizable, low-level CSS
                    framework that gives you all of the building blocks you need
                    to build bespoke designs without any annoying opinionated
                    styles you have to fight to override.
                  </div>
                </div>
              </div>

              <div className="border-t border-gray-200 p-6  md:border-l">
                <div className="flex items-center">
                  <CodeBracketIcon className="h-8 w-8 text-gray-500" />
                  <div className="ml-4 text-lg font-semibold leading-7 text-gray-900 ">
                    About this Template
                  </div>
                </div>

                <div className="ml-12">
                  <div className="mt-2 text-sm text-gray-600 ">
                    This starter kit is composed of{" "}
                    <a
                      href="https://nextjs.org"
                      className="underline"
                      target="_blank"
                      rel="noreferrer"
                    >
                      Next.js
                    </a>{" "}
                    and{" "}
                    <a
                      href="https://tailwindcss.com"
                      className="underline"
                      target="_blank"
                      rel="noreferrer"
                    >
                      Tailwind CSS
                    </a>
                    , with{" "}
                    <a
                      href="https://docs.family.co/connectkit"
                      className="underline"
                      target="_blank"
                      rel="noreferrer"
                    >
                      elements from the T3 stack (Tanstack Query, tRPC,
                      TypeScript)
                    </a>{" "}
                    and auth patterns borrowed from Laravel to provide some
                    flexibility to devs migrating over!
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-4 flex justify-center sm:items-center sm:justify-between">
            <div className="text-center text-sm text-gray-500 sm:text-left">
              <div className="flex items-center">
                <a
                  href="https://twitter.com/gcavanunez"
                  className="ml-1 flex items-center space-x-2 underline"
                >
                  <ShareIcon className="-mt-px h-5 w-5 text-gray-400" />
                  <span>Share</span>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
